#! /bin/bash

for file in "$@"; do
  sed -i -E \
    -e "s/\bl ([0-9]+)/l lt \1/g" \
    -e "s/\blp ([0-9]+)/lp lt \1/g" \
    -e "s/\bp ([0-9]+)/p pt \1/g" \
    -e "s/\bi ([0-9]+)/i lt \1/g" \
    -e "s/\blines ([0-9]+)/lines lt \1/g" \
    -e "s/\blinesp ([0-9]+)/linesp lt \1/g" \
    -e "s/\berrorbars ([0-9]+)/errorbars lt \1/g" \
    -e "s/\be ([0-9]+)/e/g" \
    -e "s/\bl pt ([0-9]+)/l lt \1/g" \
    $file
done
