#! /bin/bash

makefile="Makefile"
echo -e "default: all\n" > $makefile

declare -a targets
for file in "$@"; do
  infile=$(egrep "^i:" $file | cut -f 2-)
  outfile=$(egrep "^o:" $file | cut -f 2-)
  creator=$(egrep "^# Creator:" $file | cut -f 2-)
  args="$(cat $file | grep -v "^#" | sed 's/^\(.\):\?[[:space:]]*/-\1 /')"
  if [[ -z $creator ]]; then
    echo "Warning: no creator given for '$file'!!"
    continue
  fi
  targets+=("$outfile")
  echo "$outfile: $infile $file \$(shell which $creator)" >> $makefile
  echo -e "\t$creator $(echo $args)\n" >> $makefile
done

echo ".PHONY: all clean" >> $makefile
echo -e "all: " "${targets[@]}" >> $makefile

declare -a cleanup
for file in "${targets[@]}"; do
  cleanup+=("$file" "$file.gp" "$file.eps")
done

echo -e "clean:\n\trm -f " "${cleanup[@]}" "Makefile \n" >> $makefile
