#!/bin/sh

if [ "$TERM" = "linux" ]; then 
	exit;
fi

if ! (xlsclients | grep "xdvi.*gliederung"  > /dev/null ); then
	xdvi gliederung -s 4 -copy -keep -nopostscript -yoffset 1cm -hushspecials -geometry "960x736+0+768" $* &
	ps -x > /dev/null
	#sleep 1s
	until ( (xwininfo -root -children -tree | grep "Xdvi: gliederung") > /dev/null ); do ls>/dev/null ; done
fi
