#!/bin/bash

for i in ../orig/*.gp; do 
	j=`basename $i .gp`
	s="xsvd`echo $j|cut -d"s" -f2-`"
	k="tssf`echo $j|cut -d"s" -f2-`"
	svd -i ../orig/$j -o $s -n -w 17
	svdrec -i ../orig/$j -s $s -o $k -d 1
done

