#! /bin/bash

export PATH=$HOME/.local/tsa/bin/:$PATH

declare -a dirs
dirs=(
  attraktoren
  autocorr
  corrint/perfect
  corrint/errors/discrete
  corrint/errors/lacunarity
  corrint/errors/lacunarity/cantor
  corrint/errors/noise
  corrint/errors/noise/svd/low
  corrint/errors/noise/svd/high
  density
)

for dir in "${dirs[@]}"; do
  echo -e "DIR: $dir\n=============================================================="
  (cd $dir; prepdir)
  #(cd $dir; make clean)
  echo ""
done
