CPPFLAGS := -I../../../code/minilibg++/
CXXFLAGS := -fpermissive

# You must have build the code with something like "cmake -S code -B build" from the project root
discrim: discrim.cc ../../../build/minilibg++/libminilibg++.a

# Something like that is also missing here... (but it takes quite a while and I am not soo sure about it...)
#stat:
#	./discrim
