all: bla sevena sevenb sixa sixb three

bla: bla.cc

sevena: bla
	./bla 4 1100011 > sevena

sevenb: bla
	./bla 4 1010101 > sevenb

sixa: bla
	./bla 4 110011 > sixa

sixb: bla
	./bla 4 101101 > sixb

three: bla
	./bla 4 101 > three
