name: Build executables from C++ sources
on: [push]

jobs:
  build_cpp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
	  sudo apt-get -y update
	  sudo apt-get -y upgrade
	  sudo apt-get -y install cmake g++
	  
      - name: Compile LaTeX document
        run: |
          mkdir build
	  cmake -S code -B build
	  cd build
	  make
