name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v3
        with:
          texlive_version: 2024
          run: |
            cd doc
            make
            mv gliederung.pdf diplomarbeit_ezander_tsa_1998.pdf
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: diplomarbeit_ezander
          path: doc/diplomarbeit_ezander_tsa_1998.pdf

      - name: Deploy PDF to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: doc/diplomarbeit_ezander_tsa_1998.pdf
          destination_dir: docs
          
