name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install texlive-latex-base texlive-fonts-extra texlive-lang-german texlive-font-utils

    - name: Make PDF and PS output
      run: make
