name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: texlive-latex-base texlive-fonts-extra texlive-lang-german texlive-font-utils
        version: 1.1
        execute_install_scripts: true
              
#    - name: Install dependencies
#      run: echo sudo apt-get install texlive-latex-base texlive-fonts-extra texlive-lang-german texlive-font-utils

    - name: Make PDF and PS output
      run: make

    - name: Archive outputs
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./gliederung.pdf
          ./gliederung.ps
